[theme]
# Primary color for interactive elements
primaryColor = "#ff6b35"

# Background color for the main content area
backgroundColor = "#0e1117"

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = "#1a1d24"

# Color used for almost all text
textColor = "#fafafa"

# Font family for all text in the app
font = "sans serif"
